---
all:
  hosts:
    laptop:
      # Для чистого локального Arch. Для удалённой машины замените на ansible_host/ansible_user.
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python

      # ВАЖНО: замените на имя основного пользователя ноутбука.
      laptop_user: xoma

      # Клавиатура в niri по умолчанию: us,ru с переключением Alt+Shift.
      # niri_keyboard_layout: "us,ru"
      # niri_keyboard_options: "grp:alt_shift_toggle"

      # По умолчанию greetd только включается в автозагрузку. Если хотите стартовать сразу:
      # laptop_start_greetd_now: true
